In [13]:
import numpy as np

y_pred = np.array([1,1,0,0,1])
y_true = np.array([0.30,0.7,1,0,0.5])

In [24]:
#writing the fuctions for total error, Mean absolute error , mean square error
def mae(y_true, y_pred):
  total_error = 0
  for yt, yp in zip (y_true, y_pred):
    total_error += abs(yt -yp)
  print("Total error:", total_error)
  mae = total_error / len(y_true)
  print("total mae:", mae)
  #return mae


In [19]:
mae(y_true, y_pred)

Total error: 2.5
total mae: 0.5


In [23]:
#Doing the same fuction as above using numpy :
np.mean(np.abs(y_pred - y_true))

0.5

In [26]:
np.log([0.000001])

array([-13.81551056])

In [27]:
eplison = 1e-15

In [28]:
y_pred

array([1, 1, 0, 0, 1])

In [39]:
y_pred_new = [ max(i , eplison )for i in y_pred]
y_pred_new


[1, 1, 1e-15, 1e-15, 1]

In [40]:
y_pred_new = [min(i,1-eplison) for i in y_pred_new]
y_pred_new

[0.999999999999999, 0.999999999999999, 1e-15, 1e-15, 0.999999999999999]

In [41]:
y_pred_new = np.array(y_pred_new)
np.log(y_pred_new)

array([-9.99200722e-16, -9.99200722e-16, -3.45387764e+01, -3.45387764e+01,
       -9.99200722e-16])

In [42]:
-np.mean(y_true*np.log(y_pred_new)+(1-y_true)*np.log(1-y_pred_new))

17.2696280766844

In [43]:
def log_loss (y_true, y_pred):
  epsilon = 1e-15
  y_pred_new = [ max(i , eplison )for i in y_pred]
  y_pred_new = [min(i,1-eplison) for i in y_pred_new]
  y_pred_new = np.array(y_pred_new)
  return -np.mean(y_true*np.log(y_pred_new)+(1-y_true)*np.log(1-y_pred_new))





In [44]:
log_loss(y_true, y_pred_new)

17.2696280766844

#implement mean square error (or MLE)